import { AfterViewInit, ElementRef, EventEmitter, IterableDiffers } from '@angular/core';
import { DatasetApiInterface, DatasetPresenterComponent, InternalIdHandler, PresenterHighlight, Time, TimedDatasetOptions } from '@helgoland/core';
import { LangChangeEvent, TranslateService } from '@ngx-translate/core';
export declare class PlotlyProfileGraphComponent extends DatasetPresenterComponent<TimedDatasetOptions[], any> implements AfterViewInit {
    protected iterableDiffers: IterableDiffers;
    protected api: DatasetApiInterface;
    protected datasetIdResolver: InternalIdHandler;
    protected timeSrvc: Time;
    protected translateSrvc: TranslateService;
    onHighlight: EventEmitter<PresenterHighlight>;
    plotlyElem: ElementRef;
    private plotlyArea;
    private preparedData;
    private rawData;
    private counterXAxis;
    private counterYAxis;
    private layout;
    private settings;
    constructor(iterableDiffers: IterableDiffers, api: DatasetApiInterface, datasetIdResolver: InternalIdHandler, timeSrvc: Time, translateSrvc: TranslateService);
    ngAfterViewInit(): void;
    protected onLanguageChanged(langChangeEvent: LangChangeEvent): void;
    reloadDataForDatasets(datasetIds: string[]): void;
    protected timeIntervalChanges(): void;
    protected addDataset(id: string, url: string): void;
    protected removeDataset(internalId: string): void;
    protected setSelectedId(internalId: string): void;
    protected removeSelectedId(internalId: string): void;
    protected presenterOptionsChanged(options: any): void;
    protected datasetOptionsChanged(internalId: string, options: TimedDatasetOptions[], firstChange: boolean): void;
    protected onResize(): void;
    private processData();
    private createXAxis(dataset, data);
    private createYAxis(dataset, data);
    private updateAxis();
    private drawChart();
    private clearLayout();
    private clearData();
    private redrawChart();
}
